### ISSUE TITLE
Can I use in Python mode?

### ISSUE THREAD

**Issue by astoctas** [openpatch/scratch-for-java#4]
Could you give an example? Thanks, regards!

**Comment by mikebarkmin** [comment]
You can use it in Python mode. Here is an example

```
add_library('sound')
add_library('scratch')

def setup():
    size(480, 360)
    ScratchStage.init(this)
    stage = ScratchStage.getInstance()
    
    pumpkin = PumpkinSprite()
    stage.addSprite(pumpkin)
    
    
def draw():
    pass
    
class PumpkinSprite(ScratchSprite):
    def __init__(self):
        self.addCostume("pumpkin01", "pumpkin01.png")
        self.addCostume("pumpkin02", "pumpkin02.png")
        self.setPosition(100, 100)
        self.setSize(20)
        self.setOnEdgeBounce(True)
        self.addTimer("move")
    
    def run(self):        
        if self.getTimer().everyMillis(200):
            self.nextCostume()
        if self.getTimer("move").everyMillis(2000):
            self.move(10)
```
pumpkin01.png
![pumpkin01](https://user-images.githubusercontent.com/2592379/89006170-64a4ae00-d306-11ea-8d33-20bb8697eb14.png)

pumpkin02.png
![pumpkin02](https://user-images.githubusercontent.com/2592379/89006171-653d4480-d306-11ea-93e8-b17d8a4b7fcd.png)

**Comment by astoctas** [comment]
Hi, thanks for the answer.

I've tried something like that but gives me this error: 

sketch_200731a.pyde:1: RuntimeWarning: PyTableCode.call caught a Throwable that is not an Exception:
java.lang.NoClassDefFoundError: Lprocessing/sound/SoundFile;
Jython internals might be in a bad state now that can cause deadlocks later on.
See http://bugs.jython.org/issue2536 for details.
  add_library('scratch')

Could you help?
Thanks, regards.

**Comment by mikebarkmin** [comment]
Can you try installing processing sound and put a `add_library("sound")` at the beginning of.your file before `add_library("scratch")`.
